insert into pets (
    id,
    name,
    grade,
    nickname,
    skill_name,
    skill_target,
    skill_description_lines
) values
    ('dello', '델로', 'legend', '작은 사신', '펫의 응원', '모든 아군', '["치명타 확률 21% 증가","치명타 피해 15% 증가"]'::jsonb),
    ('doo', '두', 'rare', '행운의 탐험가', '펫의 응원', null, '["모험에서 장비 및 장신구 획득 확률 10% 증가"]'::jsonb),
    ('durgi', '더지', 'legend', '영리한 탐험가', '펫의 응원', null, '["모험에서 장비 및 장신구 획득 확률 30% 증가"]'::jsonb),
    ('eri', '에리', 'legend', '행복을 전하는', '펫의 응원', null, '["모험에서 영웅 획득 확률 10% 증가"]'::jsonb),
    ('helepin', '헬레핀', 'rare', '발키리의 그리폰', '펫의 응원', '모든 아군', '["막기확률 17% 증가"]'::jsonb),
    ('irin', '이린', 'legend', '사냥터의 왕', '펫의 응원', '모든 아군', '["물리공격력 21% 증가"]'::jsonb),
    ('karam', '카람', 'legend', '푸른 화령', '펫의 응원', '모든 아군', '["받는 피해량 8% 감소","막기 확률 15% 증가"]'::jsonb),
    ('kri', '크리', 'legend', '복수의 악마', '펫의 응원', '모든 아군', '["효과 적중 19% 증가","모든 공격력 12% 증가"]'::jsonb),
    ('kroa', '크로아', 'rare', '심연의 상징', '펫의 응원', '모든 아군', '["모든 공격력 12% 증가"]'::jsonb),
    ('melpe', '멜패로', 'legend', '혼돈의 흑조', '펫의 응원', '모든 아군', '["효과 적용 확률 10% 증가","효과 적중 19% 증가"]'::jsonb),
    ('mick', '믹', 'legend', '황금 상자', '펫의 응원', null, '["모험에서 골드 20% 추가 획득"]'::jsonb),
    ('mimic', '미믹', 'rare', '반짝이는 상자', '펫의 응원', null, '["모험에서 골드 10% 추가 획득"]'::jsonb),
    ('mumu', '뮤뮤', 'rare', '천둥 신선', '펫의 응원', '모든 아군', '["주는 피해량 10% 증가"]'::jsonb),
    ('nikki', '니키', 'rare', '완전체 쥐', '펫의 응원', '모든 아군', '["효과 적중 25% 증가"]'::jsonb),
    ('nina', '니나', 'rare', '감동의 정화', '펫의 응원', '모든 아군', '["치명타 확률 17% 증가"]'::jsonb),
    ('note', '노트', 'rare', '대도서관', '펫의 응원', '모든 아군', '["마법 공격력 17% 증가"]'::jsonb),
    ('paragon', '파라곤', 'rare', '하늘의 눈', '펫의 응원', '모든 아군', '["방어력 17% 증가"]'::jsonb),
    ('pike', '파이크', 'legend', '따뜻한 눈보라', '펫의 응원', '모든 아군', '["효과 저항 19% 증가","방어력 13% 증가"]'::jsonb),
    ('poong', '풍소협', 'rare', '호위 무사', '펫의 응원', '모든 아군', '["치명타 피해 25% 증가"]'::jsonb),
    ('richel', '리첼', 'legend', '고귀한 귀족', '펫의 응원', '모든 아군', '["약점 공격 확률 17% 증가","약점 공격 피해량 10% 증가"]'::jsonb),
    ('roo', '루', 'legend', '축복의 천사', '펫의 응원', '모든 아군', '["방어력 22% 증가"]'::jsonb),
    ('seri', '세리', 'rare', '세인의 친구', '펫의 응원', '모든 아군', '["물리 공격력 17% 증가"]'::jsonb),
    ('windy', '윈디', 'legend', '대마법사의 조력', '펫의 응원', '모든 적군, 모든 아군', '["보스가 받는 피해량 26% 증가","모든 공격력 12% 증가"]'::jsonb),
    ('yeonji', '연지', 'legend', '잠을 인도하는', '펫의 응원', '모든 아군', '["마법 공격력 21% 증가"]'::jsonb),
    ('yu', '유', 'legend', '총운의 정령', '펫의 응원', '모든 적군', '["방어력 10% 감소","받는 회복량 32% 감소"]'::jsonb)
on conflict (id) do update
set name = excluded.name,
    grade = excluded.grade,
    nickname = excluded.nickname,
    skill_name = excluded.skill_name,
    skill_target = excluded.skill_target,
    skill_description_lines = excluded.skill_description_lines;
